kind: Deployment
apiVersion: apps/v1

metadata:
  name: my-deployment

spec:
  replicas: 3
  selector:
    matchLabels: 
      app.kubernetes.io/name: django-app

  template:
    metadata:
      labels:
        app.kubernetes.io/name: django-app

    spec:
      containers:
        - name: django-app-container
          image: hackerspider09/python-rolling-app:v1
          imagePullPolicy: IfNotPresent

---

kind: Service
apiVersion: v1 
metadata:
  name: my-service

spec:
  selector:
    app.kubernetes.io/name: django-app
  
  type: LoadBalancer

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000  #this is target port on which svc should route request

# 